# Generated by Django 4.2.7 on 2023-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(blank=True, default=None, max_length=10000)),
                ('movie_title', models.CharField(blank=True, default=None, max_length=10000)),
                ('actor_name', models.CharField(blank=True, default=None, max_length=10000)),
                ('category', models.CharField(blank=True, default=None, max_length=10000)),
                ('publish_date', models.CharField(blank=True, default=None, max_length=10000)),
                ('source', models.CharField(blank=True, default=None, max_length=10000)),
                ('context', models.CharField(blank=True, default=None, max_length=10000)),
                ('rating', models.CharField(blank=True, default=None, max_length=10000)),
                ('language', models.CharField(blank=True, default=None, max_length=10000)),
                ('author', models.CharField(blank=True, default=None, max_length=10000)),
                ('author_bio', models.CharField(blank=True, default=None, max_length=10000)),
            ],
        ),
    ]
