# Generated by Django 4.2.7 on 2023-11-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='actor_name',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author_bio',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='language',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='movie_title',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='publish_date',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='rating',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(blank=True, default='Null', max_length=10000),
        ),
    ]
